name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #BUILDING THE IMAGE OF DOCKER
    #####  - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t alandocker97/react-app -f Dockerfile.dev .
      - run: docker run -e CI=true alandocker97/react-app npm test
   
      #GENERATING A DEPLOYMENT PACKAGE
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      #DEPLOYING APP TO ELASTIC BEANSTALK
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-1-622233144821
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
